### ISSUE TITLE
Add Movie Quotes

### ISSUE THREAD

**Issue by Snipey** [Snipey/popular-quotes#2]
Add movie quotes to `data/movies.json`

**Comment by sernadesigns** [comment]
I'd love to add some movie quotes to this!

**Comment by sernadesigns** [comment]
I have 10 quotes to add. Do they need to be approved first?

**Comment by sernadesigns** [comment]
PR [#36](https://github.com/Snipey/popular-quotes/pull/36) for this change.

**Comment by ImShakthi** [comment]
Have added movie quotes from **The GodFather**.  PR #38 , yet the Travis CI is failing since its not able to locate `require('../../data/books.json')` file in ` FAIL  __tests__/books/valid.test.js`.
