### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by Snipey** [Snipey/popular-quotes#26]
Still learning the whole testing thing but I think Im doing it wrong and travis is not liking it.

**Comment by adityaarakeri** [comment]
mind if a take a look? watch for a PR

**Comment by Snipey** [comment]
Sure thing :) jump on in.

**Comment by adityaarakeri** [comment]
looks like the Travis build has passed 🎉
https://github.com/Snipey/popular-quotes/pull/35

**Comment by Snipey** [comment]
Looks like it's fixed. Now for the random function tests
