### ISSUE TITLE
Compress the code down for a smaller package size

### ISSUE THREAD

**Issue by Snipey** [Snipey/popular-quotes#61]
I wrote this package in a haste and am looking for any suggestions on how to refactor the package.

Any help is much appriciated 👍

**Comment by souravdasslg** [comment]
Hi @Snipey , for any instances have you considered uglifying the entire codebase?

**Comment by souravdasslg** [comment]
Another idea is to create a single bundle file after uglifying the source codes. I'd love to contribute here as I love to tweak things :)

**Comment by Snipey** [comment]
Sure thing @souravdasslg 👍 I was considering taking the application logic down to a single file and load the data based on a type property passed through the functions.

**Comment by souravdasslg** [comment]
I'll start working on that very soon. Can you please assign the issue till then? It's easy for me to keep track of my tasks :)

**Comment by souravdasslg** [comment]
> Sure thing @souravdasslg  I was considering taking the application logic down to a single file and load the data based on a type property passed through the functions.

Are you up for this? I was able to bundle up the entire codebase in a single file using parcel js. Although it has not created a huge difference in the bundle size.
