### ISSUE TITLE
Refactoring the entire application

### ISSUE THREAD

**Issue by souravdasslg** [Snipey/popular-quotes#80]
Entire codebase needs to be refactored for better development, maintenance, and distribution.
**This issue will focus on**
1. Efficient distribution of code files
2. Quote management on source code.

**Comment by souravdasslg** [comment]
@Snipey  Have you any other thought regarding how would you like to put the JSON files in the application? I was thinking, keeping all the quotes inside the source code will increase the bundle size.

**Comment by Snipey** [comment]
Any suggestions to how it can be achieved?

**Comment by Snipey** [comment]
Someone suggested that the entries get added to a sqlite db and shipped with the package but i think that might add too much overhead and a dependency that is unwanted.

**Comment by souravdasslg** [comment]
Not a good idea though. My idea is to work with BSON or any other efficient serialization techniques.
But that will add another dependency in the library.

Though, we can read JSON stream instead of reading the entire JSON file to make it memory efficient.

**Comment by souravdasslg** [comment]
I have reorganized the code base a bit. Next idea is dynamic loading of JSON based upon user request.
If the user imports movie quotes, all others can be skipped. It will help in memory utilization if we are going to store quotes in JSON only. I'd like to hear you on this
